services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/api.Dockerfile
    container_name: auto-search-api
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.prod
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/api/v1/health')"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - internal

  ingest-worker:
    build:
      context: ../../
      dockerfile: apps/ingest-worker/Dockerfile
    container_name: auto-search-ingest-worker
    env_file:
      - .env.prod
    environment:
      - TG_API_ID=34456629
      - TG_API_HASH=b54959eed146203ec150e86cbe990bdd
      - TG_SESSION_STRING=1ApWapzMBu1V9weXSsqzcO_HzhyDp6jLMd_zve467mf-SkTdTvMobhRH8oAz-p_PvtH5pIZA_dpx1B6rTOIoTDDqSSSaMnx6DtObcfsjA_zyNzSr2h4pk-fpvNqOmEDWYlyUDVkYK8k7Y4PZFHDy1F5ryJnk4Vck-BM9sRgp6SUOFX6B5_MkQAO04MjzPqJwlYlzga6CZ1_TDrW2GRQAYQNQ6A_PXz23IoDETphllA4lJ9fFMQfEYud7kIg-7Xuef1Jj-FwMz3WWGaBv3oG_xSgJAHRik3PmhBMge4KwDpmGabF3IQ7_bcY6KB2EBJiOckLBO0FQMCPgih6WuBlNUzkhUip_kZEM=
      - TG_CHANNELS=@autoru_official,@cars_ru,@car_market_ru,@mercedesclubrussia,@mbmarket_ru,@bmwclubrussia,@bmwmarket,@chinamarket_auto,@lixiang_russia
      - TG_FETCH_LIMIT=50
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"
    networks:
      - internal

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: auto-search-web
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - api
    restart: always

  postgres:
    image: postgres:16-alpine
    container_name: auto-search-postgres
    restart: always
    environment:
      POSTGRES_DB: auto_search
      POSTGRES_USER: auto
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auto -d auto_search -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: auto-search-redis
    restart: always
    command: ["redis-server", "--protected-mode", "yes", "--save", "60", "1", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - internal

  qdrant:
    image: qdrant/qdrant:v1.10.1
    container_name: auto-search-qdrant
    restart: always
    volumes:
      - qdrant_data:/qdrant/storage
    networks:
      - internal

volumes:
  postgres_data:
  qdrant_data:

networks:
  internal:
    driver: bridge
