worker_processes auto;

events {
    worker_connections 1024;
}

http {

    limit_req_zone $binary_remote_addr zone=api:10m rate=5r/s;

    upstream api_upstream {
        server auto-search-api:8000;
        keepalive 32;
    }

    gzip on;
    gzip_comp_level 5;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types
        text/plain
        text/css
        application/json
        application/javascript
        application/xml
        text/xml
        text/javascript;

    server {
        listen 80;

        location /api/ {
            limit_req zone=api burst=20 nodelay;
            proxy_pass http://api:8000;
        }

        location / {
            proxy_pass http://api_upstream;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header Connection "";

            proxy_read_timeout 60;
            proxy_connect_timeout 10;
        }
    }
}